/**/mqtt_client:
  ros__parameters:
    broker:
      host: '6568851381634f73af5c5631e79edcce.s1.eu.hivemq.cloud'
      port: 8883
      user: 'ground_station1'
      pass: 'Ground_station1'
      tls:
        enabled: true

    bridge:
      mqtt2ros:
        mqtt_topics: 
          - 'waraps/unit/surface/real/origin_gps'
          - 'waraps/unit/surface/real/MiniUSV1/sensor/gps'
          - 'waraps/unit/surface/real/MiniUSV1/sensor/heading'
          - 'waraps/unit/surface/real/MiniUSV2/sensor/gps'
          - 'waraps/unit/surface/real/MiniUSV2/sensor/heading'
          - 'waraps/unit/surface/real/MiniUSV2/control/throttle'
          - 'waraps/unit/surface/real/MiniUSV2/control/steering'
        waraps/unit/surface/real/origin_gps:
          ros_topic: 'origin_gps'
        waraps/unit/surface/real/MiniUSV1/sensor/gps:
          ros_topic: 'usv1/gps'
        waraps/unit/surface/real/MiniUSV1/sensor/heading:
          ros_topic: 'usv1/heading'
        waraps/unit/surface/real/MiniUSV2/sensor/gps:
          ros_topic: 'usv2/gps'
        waraps/unit/surface/real/MiniUSV2/sensor/heading:
          ros_topic: 'usv2/heading'
        waraps/unit/surface/real/MiniUSV2/control/throttle:
          ros_topic: 'follower/control/throttle'
        waraps/unit/surface/real/MiniUSV2/control/steering:
          ros_topic: 'follower/control/steering'